# Generated by Django 6.0.3 on 2026-07-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_user_account_locked_until_user_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='user',
          field=models.ForeignKey(
    null=True,
    blank=True,
    on_delete=django.db.models.deletion.CASCADE,
    to='gallery.user'
),
            preserve_default=False,
        ),
    ]
